// Chromium interaction checks for batch actions, using an isolated fake desktop bridge.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {existsSync,readFileSync,writeFileSync,mkdtempSync,rmSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {basename,dirname,resolve,sep} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const repo=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const args=process.argv.slice(2), option=name=>args.includes(name)?args[args.indexOf(name)+1]:null;
const browserPath=option('--browser') || process.env.SKILL_RADAR_BROWSER;
assert(browserPath && existsSync(browserPath),'Provide Chromium with --browser');
const htmlPath=resolve(option('--html') || resolve(repo,'tray/web/index.html'));
const captureDir=option('--capture'), prefix=option('--prefix') || 'batch';
const width=Number(option('--width') || 1080),height=Number(option('--height') || 720);
const language=option('--language') || 'zh-CN', profile=mkdtempSync(resolve(tmpdir(),'skill-radar-batch-ui-'));
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const risk={severity:'CRITICAL',rule_id:'UPLOAD_PRIVATE',file:'scripts/setup.sh',line:4,message:'发现可能读取并上传本机私密文件的指令。',excerpt:'sensitive content'};
const row=(name,extra={})=>({name,score:0,status:'baseline-unreviewed',version:'v1-'+name,
  findings:[],raw_findings:[],raw_score:0,scan_complete:true,scan_issues:[],check_status:'healthy',review_status:'not_required',...extra});
const state={guard:'running',watched_roots:1,settings:{language:'zh-CN',roots:[{path:'F:\\Skills'}]},skills:{
  'F:\\Skills\\danger':row('danger',{status:'blocked',score:0,raw_score:46,raw_findings:[risk],check_status:'attention',review_status:'pending'}),
  'F:\\Skills\\trusted':row('trusted',{status:'trusted',score:0,raw_score:46,raw_findings:[risk],check_status:'attention',review_status:'trusted'}),
  'F:\\Skills\\healthy':row('healthy'),
  'F:\\Other\\danger':row('danger',{raw_score:35,raw_findings:[{...risk,severity:'HIGH'}],check_status:'attention',review_status:'pending'}),
  'F:\\Skills\\incomplete':row('incomplete',{scan_complete:false,check_status:'incomplete',review_status:'pending',scan_issues:['read_failed']}),
},quarantine:[{id:'q1',name:'isolated-demo',original_path:'F:\\Skills\\isolated-demo',path:'C:\\Demo\\quarantine\\q1',destination:'C:\\Demo\\quarantine\\q1',version:'q-version',reason:'Serious risk',isolated_at:'2026-10-04T10:00:00',status:'isolated'}],events:[]};
const bridge=`window.__batch_boot=crypto.randomUUID();window.__batch_state=${JSON.stringify(state)};
window.__batch_actions=[];window.__batch_autofinish=true;
try{localStorage.clear();}catch{}
window.pywebview={api:{get_state:async()=>structuredClone(window.__batch_state),act:async(name,payload)=>{
window.__batch_actions.push({name,payload});
if(name==='set_language'){window.__batch_state.settings.language=payload.language;return{ok:true};}
if(name!=='batch_action')return{ok:true,output:'Changes'};
const id='job-'+window.__batch_actions.length;
window.__batch_state.batch_job={id,action:payload.action,status:'running',items:structuredClone(payload.items),total:payload.items.length,completed:0,results:[]};
if(window.__batch_autofinish)setTimeout(()=>{
const job=window.__batch_state.batch_job;job.status='done';job.completed=job.total;
job.results=job.items.map((item,i)=>({...item,status:i===1?'failed':i===2?'skipped':'success',code:i===1?'move_failed':i===2?'version_changed':'ok'}));
if(payload.action==='review')for(const item of payload.items){const row=window.__batch_state.skills[item.path];if(row)row.review_status='reviewed';}
},80);
return{ok:true,job_id:id};
}}};`;
let browser,ws,closeBrowser;const results=[];
try{
browser=spawn(browserPath,['--headless=new','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
browser.on('error',error=>results.push({name:'browser_start',ok:false,error:error.message}));
const portFile=resolve(profile,'DevToolsActivePort');let until=Date.now()+12000;
while(!existsSync(portFile)&&Date.now()<until)await pause(40);
assert(existsSync(portFile),'Chromium did not expose its temporary endpoint');
const port=readFileSync(portFile,'utf8').split(/\r?\n/)[0];
const target=(await(await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(p=>p.type==='page');
ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((ok,fail)=>{ws.addEventListener('open',ok,{once:true});ws.addEventListener('error',fail,{once:true});});
let id=0;const pending=new Map();
ws.addEventListener('message',event=>{const data=JSON.parse(event.data),request=pending.get(data.id);if(!request)return;pending.delete(data.id);clearTimeout(request.timeout);data.error?request.reject(new Error(JSON.stringify(data.error))):request.resolve(data.result);});
const cdp=(method,params={})=>new Promise((ok,fail)=>{const current=++id,timeout=setTimeout(()=>{pending.delete(current);fail(new Error('CDP timeout '+method));},8000);pending.set(current,{resolve:ok,reject:fail,timeout});ws.send(JSON.stringify({id:current,method,params}));});
closeBrowser=()=>cdp('Browser.close');
const evaluate=async expression=>{const value=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});assert(!value.exceptionDetails,JSON.stringify(value.exceptionDetails));return value.result.value;};
const waitFor=async expression=>{const deadline=Date.now()+2000;while(Date.now()<deadline){if(await evaluate(expression))return;await pause(25);}throw new Error('UI condition: '+expression);};
const click=async selector=>{const point=await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});if(!el)return null;el.scrollIntoView({block:'center'});const r=el.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,width:r.width,height:r.height};})()`);assert(point?.width&&point.height,'Missing visible target: '+selector);for(const type of ['mousePressed','mouseReleased'])await cdp('Input.dispatchMouseEvent',{type,x:point.x,y:point.y,button:'left',clickCount:1});};
const key=async(key,code,keyCode)=>{for(const type of ['keyDown','keyUp'])await cdp('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:keyCode,nativeVirtualKeyCode:keyCode});};
const search=async query=>evaluate(`(()=>{const input=document.getElementById('skill-search');input.value=${JSON.stringify(query)};input.dispatchEvent(new Event('input',{bubbles:true}));})()`);
const sync=()=>evaluate('tick()');
await cdp('Page.enable');await cdp('Runtime.enable');
await cdp('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});
await cdp('Page.addScriptToEvaluateOnNewDocument',{source:bridge});
const reset=async()=>{const previous=await evaluate('window.__batch_boot');await cdp('Page.navigate',{url:pathToFileURL(htmlPath).href});await waitFor(`window.__batch_boot!==${JSON.stringify(previous)} && !!document.querySelector('#sec-rows tr[data-skill]')`);await click('nav.sidebar button[data-screen="security"]');};
const selected=()=>evaluate(`document.querySelectorAll('#sec-rows input.skill-select:checked').length`);
const first=()=>click('#sec-rows input.skill-select');
const openConfirm=async action=>{await first();await click(`[data-batch-action="${action}"]`);};
const screenshot=async name=>{if(!captureDir)return;await evaluate(`changeLanguage(${JSON.stringify(language)})`);await evaluate(`if(document.getElementById('drawer').hidden)document.getElementById('main-content').scrollTop=0`);mkdirSync(captureDir,{recursive:true});const audit=await evaluate(`(()=>{const main=document.getElementById('main-content'),drawer=document.getElementById('drawer');return{overflow:document.documentElement.scrollWidth>innerWidth+1||main.scrollWidth>main.clientWidth+1||(!drawer.hidden&&drawer.scrollWidth>drawer.clientWidth+1)};})()`);results.push({name:'layout_'+name,ok:!audit.overflow,...audit});const data=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(resolve(captureDir,prefix+'-'+name+'.png'),Buffer.from(data.data,'base64'));await evaluate(`changeLanguage('zh-CN')`);};
const check=async(name,fn)=>{try{await reset();await fn();results.push({name,ok:true});}catch(error){results.push({name,ok:false,error:error.stack||error.message});}};
await check('selection_current_filter',async()=>{await click('.filter[data-filter="attention"]');await click('#select-filtered');assert.equal(await selected(),4);assert.equal(await evaluate(`document.getElementById('drawer').hidden`),true);await screenshot('selected');});
await check('selection_all_matching_not_viewport',async()=>{await evaluate(`for(let i=0;i<24;i++)window.__batch_state.skills['F:\\Skills\\extra'+i]=${JSON.stringify(row('extra'))};`);await sync();await click('#select-filtered');assert.equal(await selected(),29);});
await check('selection_search_clears',async()=>{await first();await search('danger');assert.equal(await selected(),0);assert.equal(await evaluate(`document.getElementById('batch-toolbar').hidden`),true);});
await check('selection_filter_clears',async()=>{await first();await click('.filter[data-filter="attention"]');assert.equal(await selected(),0);});
await check('selection_poll_preserves',async()=>{await click('#select-filtered');assert.equal(await selected(),5,'All five must be selected before refresh');await evaluate(String.raw`window.__batch_state.skills['F:\\Skills\\new']=structuredClone(window.__batch_state.skills['F:\\Skills\\healthy']);`);await sync();assert.equal(await selected(),5);assert.equal(await evaluate(String.raw`Array.from(document.querySelectorAll('#sec-rows tr')).find(el=>el.dataset.skill==='F:\\Skills\\new').querySelector('input').checked`),false);});
await check('selection_version_change',async()=>{await first();const path=await evaluate(`document.querySelector('#sec-rows input:checked').dataset.path`);await evaluate(`window.__batch_state.skills[${JSON.stringify(path)}].version='new-version'`);await sync();assert((await evaluate(`document.getElementById('sec-rows').innerText`)).includes('内容已更新'));assert.equal(await selected(),1);});
await check('checkbox_does_not_open_detail',async()=>{await first();assert.equal(await evaluate(`document.getElementById('drawer').hidden`),true);});
await check('healthy_without_pending',async()=>{const healthy=await evaluate(String.raw`Array.from(document.querySelectorAll('#sec-rows tr')).find(el=>el.dataset.skill==='F:\\Skills\\healthy').innerText`);assert(healthy.includes('检查正常'));assert(!healthy.includes('待确认'));await screenshot('health-and-risk');});
await check('trusted_risk_stays_red',async()=>{const value=await evaluate(String.raw`(()=>{const el=Array.from(document.querySelectorAll('#sec-rows tr')).find(el=>el.dataset.skill==='F:\\Skills\\trusted');return{text:el.innerText,critical:!!el.querySelector('.badge.crit'),score:el.querySelector('.score').innerText,badges:Array.from(el.querySelectorAll('td:nth-child(3) .badge')).map(b=>b.innerText)};})()`);assert.deepEqual(value.badges,['已信任（严重风险）']);assert(value.critical);assert.equal(value.score,'46');});
await check('trusted_severity_and_incomplete_labels',async()=>{const result=await evaluate(`(()=>{const variants=[['HIGH','已信任（高风险）'],['MEDIUM','已信任（中等风险）'],['LOW','已信任（低风险）']];return variants.map(([severity,wanted])=>({wanted,html:statusBadge({check_status:'attention',review_status:'trusted',scan_complete:true,raw_findings:[{severity}]})})).concat([{wanted:'已信任（未发现已知风险）',html:statusBadge({check_status:'healthy',review_status:'trusted',scan_complete:true,raw_findings:[]})},{incomplete:true,html:statusBadge({check_status:'incomplete',review_status:'trusted',scan_complete:false,raw_findings:[{severity:'CRITICAL'}]})}]);})()`);for(const row of result){if(row.incomplete){assert(row.html.includes('检查未完成'));assert(!row.html.includes('已信任'));}else assert(row.html.includes(row.wanted));}});
await check('incomplete_is_not_healthy',async()=>{const text=await evaluate(String.raw`Array.from(document.querySelectorAll('#sec-rows tr')).find(el=>el.dataset.skill==='F:\\Skills\\incomplete').innerText`);assert(text.includes('检查未完成'));assert(!text.includes('检查正常'));});
await check('detail_review_entry',async()=>{await click('#sec-rows tr[data-skill]');assert.equal(await evaluate(`!document.querySelector('#detail-processing [data-batch-action="review"]').hidden`),true);await click('#detail-processing [data-batch-action="review"]');await click('#btn-confirm-processing');await waitFor(`window.__batch_actions.some(a=>a.name==='batch_action'&&a.payload.action==='review')`);assert.equal(await evaluate(`window.__batch_actions.at(-1).payload.items.length`),1);});
await check('trust_confirm_exact_paths',async()=>{await search('danger');await click('#select-filtered');await click('#batch-toolbar [data-batch-action="trust"]');assert.equal(await evaluate(`window.__batch_actions.filter(a=>a.name==='batch_action').length`),0);const text=await evaluate(`document.getElementById('drawer-body').innerText`);assert(text.includes('F:\\Skills\\danger')&&text.includes('F:\\Other\\danger'));assert(text.includes('重复提醒和自动隔离'));await screenshot('trust-confirm');await click('#btn-confirm-processing');await waitFor(`window.__batch_actions.some(a=>a.name==='batch_action')`);assert.deepEqual(await evaluate(`window.__batch_actions.at(-1).payload.items.map(item=>item.path).sort()`),['F:\\Other\\danger','F:\\Skills\\danger']);});
await check('confirm_cancel_and_escape',async()=>{await openConfirm('quarantine');await key('Escape','Escape',27);assert.equal(await evaluate(`document.getElementById('drawer').hidden`),true);assert.equal(await evaluate(`document.getElementById('app-layout').inert`),false);assert.equal(await evaluate(`window.__batch_actions.filter(a=>a.name==='batch_action').length`),0);});
await check('batch_progress_reopen',async()=>{await evaluate('window.__batch_autofinish=false');await openConfirm('rescan');await click('#btn-confirm-processing');await waitFor(`document.getElementById('drawer-body').innerText.includes('0 / 1')`);await key('Escape','Escape',27);await click('#btn-batch-results');assert((await evaluate(`document.getElementById('drawer-body').innerText`)).includes('0 / 1'));assert.equal(await evaluate(`window.__batch_actions.filter(a=>a.name==='batch_action').length`),1);});
await check('batch_mixed_results',async()=>{await click('#select-filtered');await click('#batch-toolbar [data-batch-action="quarantine"]');await click('#btn-confirm-processing');await pause(100);await sync();const text=await evaluate(`document.getElementById('drawer-body').innerText`);assert(text.includes('成功')&&text.includes('失败')&&text.includes('跳过'));assert(text.includes('内容已变化'));await screenshot('mixed-result');});
await check('retry_only_failed',async()=>{await click('#select-filtered');await click('#batch-toolbar [data-batch-action="quarantine"]');await click('#btn-confirm-processing');await pause(100);await sync();const failed=await evaluate(`window.__batch_state.batch_job.results.filter(row=>row.status==='failed').map(row=>row.path)`);await waitFor(`!document.getElementById('btn-retry-failed').hidden`);await click('#btn-retry-failed');await click('#btn-confirm-processing');assert.deepEqual(await evaluate(`window.__batch_actions.at(-1).payload.items.map(row=>row.path)`),failed);});
await check('quarantine_restore_choices',async()=>{await click('#tab-quarantine');assert((await evaluate(`document.getElementById('quarantine-rows').innerText`)).includes('isolated-demo'));await click('[data-restore-action="restore"]');assert((await evaluate(`document.getElementById('drawer-body').innerText`)).includes('可能再次自动隔离'));await key('Escape','Escape',27);await click('[data-restore-action="restore_trust"]');await screenshot('restore-confirm');await click('#btn-confirm-processing');await waitFor(`window.__batch_actions.some(a=>a.name==='batch_action')`);assert.deepEqual(await evaluate(`window.__batch_actions.at(-1).payload.items`),[{path:'F:\\Skills\\isolated-demo',id:'q1',version:'q-version'}]);});
await check('restore_conflict_visible',async()=>{await evaluate(`window.__batch_state.batch_job={id:'restore-conflict',action:'restore',status:'done',total:1,completed:1,items:[{path:'F:\\Skills\\isolated-demo',id:'q1',version:'q-version'}],results:[{path:'F:\\Skills\\isolated-demo',status:'failed',code:'restore_conflict'}]}`);await sync();await click('#btn-batch-results');assert((await evaluate(`document.getElementById('drawer-body').innerText`)).includes('同名文件夹'));});
await check('revoke_trust_entry',async()=>{await search('trusted');await click('#sec-rows tr[data-skill]');await click('#detail-processing [data-batch-action="revoke_trust"]');await click('#btn-confirm-processing');assert.equal(await evaluate(`window.__batch_actions.at(-1).payload.action`),'revoke_trust');});
await check('batch_english_copy',async()=>{await evaluate(`(()=>{const select=document.getElementById('ui-language');select.value='en';select.dispatchEvent(new Event('change',{bubbles:true}));})()`);await waitFor(`document.documentElement.lang==='en'`);await click('#select-filtered');await click('#batch-toolbar [data-batch-action="trust"]');const text=await evaluate(`document.getElementById('drawer').innerText`);assert(text.includes('Trust this version'));assert(!/[\u3400-\u9fff]/.test(text));});
await check('unavailable_bridge_disables_actions',async()=>{await first();await evaluate(`window.pywebview=null`);await sync();assert.equal(await evaluate(`document.querySelector('#batch-toolbar [data-batch-action="trust"]').disabled`),true);});
await check('confirmation_keeps_selected_version',async()=>{await openConfirm('trust');const path=await evaluate(`document.querySelector('#sec-rows input:checked').dataset.path`);await evaluate(`window.__batch_state.skills[${JSON.stringify(path)}].version='updated-after-confirm'`);await sync();await click('#btn-confirm-processing');const item=await evaluate(`window.__batch_actions.at(-1).payload.items[0]`);assert.notEqual(item.version,'updated-after-confirm');});
await check('success_with_warning_visible',async()=>{await evaluate(`window.__batch_state.batch_job={id:'note-warning',action:'quarantine',status:'done',total:1,completed:1,results:[{path:'F:/Skills/warning',status:'success',code:'note_failed'}]}`);await sync();await click('#btn-batch-results');assert.equal(await evaluate(`!!document.querySelector('#drawer-body .processing-item .badge.warn')`),true);assert((await evaluate(`document.getElementById('drawer-body').innerText`)).includes('说明保存失败'));});
await check('persistence_error_visible',async()=>{await evaluate(`window.__batch_state.batch_job={id:'save-warning',action:'quarantine',status:'done',total:1,completed:1,results:[],persistence_error:'disk unavailable'}`);await sync();await click('#btn-batch-results');assert((await evaluate(`document.getElementById('drawer-body').innerText`)).includes('进度记录未保存'));});
await check('trusted_guard_not_pending',async()=>{await evaluate(`window.__batch_state.guard='alert';for(const row of Object.values(window.__batch_state.skills)){row.review_status='trusted';row.check_status='attention';row.scan_complete=true;}`);await sync();assert.equal(await evaluate(`document.getElementById('guard-title').innerText`),'暂无待处理事项');assert((await evaluate(`document.getElementById('guard-description').innerText`)).includes('已信任'));});
await check('detail_confirmation_restores_row_focus',async()=>{await click('#sec-rows tr[data-skill]');const original=await evaluate(`document.querySelector('#sec-rows tr[data-skill]').dataset.skill`);await click('#detail-processing [data-batch-action="trust"]');await key('Escape','Escape',27);assert.equal(await evaluate(`document.activeElement.dataset.skill`),original);});
await check('reviewed_change_not_pending',async()=>{await evaluate(`for(const row of Object.values(window.__batch_state.skills)){row.status='drifted';row.review_status='reviewed';row.check_status='healthy';}`);await sync();await click('.filter[data-filter="attention"]');assert.equal(await evaluate(`document.querySelectorAll('#sec-rows tr[data-skill]').length`),0);});
await check('processing_storage_failure_disables',async()=>{await evaluate(`window.__batch_state.processing_error='disk full'`);await sync();await first();assert.equal(await evaluate(`document.querySelector('#batch-toolbar [data-batch-action="trust"]').disabled`),true);assert((await evaluate(`document.getElementById('screen-security').innerText`)).includes('处理记录暂时不可用'));});
await check('rollback_failure_visible',async()=>{await evaluate(`window.__batch_state.batch_job={id:'rollback-warning',action:'restore_trust',status:'done',total:1,completed:1,results:[{path:'F:/Skills/warning',status:'failed',code:'scan_failed',rollback_error:'save failed'}]}`);await sync();await click('#btn-batch-results');assert((await evaluate(`document.getElementById('drawer-body').innerText`)).includes('撤销信任未成功'));});
await check('incomplete_detail_not_clean',async()=>{await search('incomplete');await click('#sec-rows tr[data-skill]');const text=await evaluate(`document.getElementById('drawer-body').innerText`);assert(text.includes('未完成检查，无法判断'));assert(!text.includes('未命中当前风险规则'));});
await check('confirmation_updated_warning',async()=>{await first();const path=await evaluate(`document.querySelector('#sec-rows input:checked').dataset.path`);await evaluate(`window.__batch_state.skills[${JSON.stringify(path)}].version='version-changed'`);await sync();await click('#batch-toolbar [data-batch-action="trust"]');assert((await evaluate(`document.getElementById('drawer-body').innerText`)).includes('内容已更新，处理时将跳过'));});
await check('incomplete_detail_reasons',async()=>{await evaluate(String.raw`window.__batch_state.skills['F:\\Skills\\incomplete'].scan_issues=['read_failed:scripts/private.py','binary:assets/icon.png']`);await sync();await search('incomplete');await click('#sec-rows tr[data-skill]');const text=await evaluate(`document.getElementById('drawer-body').innerText`);assert(text.includes('scripts/private.py')&&text.includes('assets/icon.png'));assert(text.includes('无法读取文件'));});
await check('quarantine_current_risk_summary',async()=>{await evaluate(`window.__batch_state.quarantine[0].raw_findings=[${JSON.stringify(risk)}];window.__batch_state.quarantine[0].version='current-policy-version'`);await sync();await click('#tab-quarantine');await click('[data-restore-action="restore_trust"]');assert.equal(await evaluate(`!!document.querySelector('#drawer-body .badge.crit')`),true);await click('#btn-confirm-processing');assert.equal(await evaluate(`window.__batch_actions.at(-1).payload.items[0].version`),'current-policy-version');});
await check('quarantine_copy_pending_retry',async()=>{await evaluate(`window.__batch_state.quarantine[0].status='copy_pending'`);await sync();await click('#tab-quarantine');const text=await evaluate(`document.getElementById('quarantine-rows').innerText`);assert(text.includes('原文件仍在'));assert.equal(await evaluate(`document.querySelectorAll('#quarantine-rows [data-restore-action]').length`),0);await click('#quarantine-rows [data-quarantine-retry]');await click('#btn-confirm-processing');assert.equal(await evaluate(`window.__batch_actions.at(-1).payload.action`),'quarantine');});
await check('batch_dynamic_text_escaped',async()=>{await evaluate(`window.__batch_state.quarantine[0].name='<img src=x onerror=window.__injected=true>';window.__batch_state.quarantine[0].original_path='F:/Skills/<svg onload=window.__injected=true>'`);await sync();await click('#tab-quarantine');await click('[data-restore-action="restore_trust"]');assert.equal(await evaluate(`!!document.querySelector('#drawer-body img,#drawer-body svg[onload],#quarantine-rows img,#quarantine-rows svg[onload]')`),false);assert.equal(await evaluate(`!!window.__injected`),false);});
await check('quarantine_refreshing_disables_restore',async()=>{await evaluate(`window.__batch_state.quarantine[0].refreshing=true;window.__batch_state.quarantine[0].scan_complete=false`);await sync();await click('#tab-quarantine');assert.equal(await evaluate(`Array.from(document.querySelectorAll('#quarantine-rows [data-restore-action]')).every(button=>button.disabled)`),true);assert((await evaluate(`document.getElementById('quarantine-rows').innerText`)).includes('正在更新隔离检查结果'));await evaluate(`changeLanguage('en')`);assert((await evaluate(`document.getElementById('quarantine-rows').innerText`)).includes('Updating quarantine check results'));});
await check('restore_confirm_refreshing_disables_submit',async()=>{await click('#tab-quarantine');await click('[data-restore-action="restore_trust"]');await evaluate(`window.__batch_state.quarantine[0].refreshing=true`);await sync();assert.equal(await evaluate(`document.getElementById('btn-confirm-processing').disabled`),true);assert((await evaluate(`document.getElementById('drawer-body').innerText`)).includes('正在更新隔离检查结果'));await evaluate(`window.__batch_state.quarantine[0].refreshing=false;window.__batch_state.quarantine[0].version='changed-rules'`);await sync();assert.equal(await evaluate(`document.getElementById('btn-confirm-processing').disabled`),true);});
await check('restore_copy_pending_warning',async()=>{await evaluate(`window.__batch_state.quarantine[0].status='restore_copy_pending';window.__batch_state.batch_job={id:'restore-copy-warning',action:'restore',status:'done',total:1,completed:1,results:[{path:'F:/Skills/isolated-demo',status:'success',code:'restore_copy_pending'}]}`);await sync();await click('#tab-quarantine');assert((await evaluate(`document.getElementById('quarantine-rows').innerText`)).includes('已恢复，隔离副本待清理'));assert.equal(await evaluate(`document.querySelectorAll('#quarantine-rows [data-restore-action],#quarantine-rows [data-quarantine-retry]').length`),0);await click('#btn-batch-results');assert.equal(await evaluate(`!!document.querySelector('#drawer-body .processing-item .badge.warn')`),true);});
if(captureDir){await reset();await click('#select-filtered');const audit=await evaluate(`({overflow:document.documentElement.scrollWidth>innerWidth+1||document.getElementById('main-content').scrollWidth>document.getElementById('main-content').clientWidth+1})`);results.push({name:'layout_security',ok:!audit.overflow,...audit});await screenshot('toolbar-layout');}
}catch(error){results.push({name:'harness',ok:false,error:error.stack||error.message});}
finally{try{if(closeBrowser)await closeBrowser();}catch{}if(ws)ws.close();if(browser&&browser.exitCode===null){browser.kill();await Promise.race([new Promise(resolve=>browser.once('exit',resolve)),pause(2000)]);}assert(profile.startsWith(resolve(tmpdir())+sep)&&basename(profile).startsWith('skill-radar-batch-ui-'));try{rmSync(profile,{recursive:true,force:true,maxRetries:6,retryDelay:150});}catch{}}
console.log(JSON.stringify({html:htmlPath,browser:browserPath,results}));process.exitCode=results.some(row=>!row.ok)?1:0;
