// Real Chromium checks for the collapsible desktop sidebar.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {existsSync,readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {basename,dirname,resolve,sep} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';

const repo=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const args=process.argv.slice(2), option=name=>args.includes(name)?args[args.indexOf(name)+1]:null;
const browserPath=option('--browser') || process.env.SKILL_RADAR_BROWSER;
assert(browserPath && existsSync(browserPath),'Provide Chromium with --browser');
const htmlPath=resolve(option('--html') || resolve(repo,'tray/web/index.html'));
const profile=mkdtempSync(resolve(tmpdir(),'skill-radar-sidebar-'));
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const state={guard:'running',watched_roots:1,settings:{language:'zh-CN',roots:[{path:'F:/Skills'}]},skills:{},events:[]};
const bridge=`window.__sidebar_boot=crypto.randomUUID();window.__sidebar_state=${JSON.stringify(state)};window.pywebview={api:{get_state:async()=>structuredClone(window.__sidebar_state),act:async()=>({ok:true})}};`;
let browser,ws,cdp;const results=[];
try{
  browser=spawn(browserPath,['--headless=new','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
  const portFile=resolve(profile,'DevToolsActivePort'),deadline=Date.now()+12000;
  while(!existsSync(portFile)&&Date.now()<deadline)await pause(40);
  assert(existsSync(portFile),'Chromium did not expose its temporary endpoint');
  const port=readFileSync(portFile,'utf8').split(/\r?\n/)[0],target=(await(await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(page=>page.type==='page');
  ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((ok,fail)=>{ws.addEventListener('open',ok,{once:true});ws.addEventListener('error',fail,{once:true});});
  let id=0;const pending=new Map();ws.addEventListener('message',event=>{const data=JSON.parse(event.data),request=pending.get(data.id);if(!request)return;pending.delete(data.id);clearTimeout(request.timeout);data.error?request.reject(new Error(JSON.stringify(data.error))):request.resolve(data.result);});
  cdp=(method,params={})=>new Promise((ok,fail)=>{const current=++id,timeout=setTimeout(()=>{pending.delete(current);fail(new Error('CDP timeout '+method));},8000);pending.set(current,{resolve:ok,reject:fail,timeout});ws.send(JSON.stringify({id:current,method,params}));});
  const evaluate=async expression=>{const result=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});assert(!result.exceptionDetails,JSON.stringify(result.exceptionDetails));return result.result.value;};
  const waitFor=async expression=>{const stop=Date.now()+3000;while(Date.now()<stop){if(await evaluate(expression))return;await pause(25);}throw new Error('UI condition: '+expression);};
  const key=async(key,code,keyCode)=>{const text=key==='Enter'?'\r':key===' '?' ':undefined;for(const type of ['keyDown','keyUp'])await cdp('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:keyCode,nativeVirtualKeyCode:keyCode,...(type==='keyDown'&&text?{text,unmodifiedText:text}:{})});};
  const click=async selector=>{const point=await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});if(!el)return null;const r=el.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,width:r.width,height:r.height};})()`);assert(point?.width&&point.height,'Missing target '+selector);for(const type of ['mousePressed','mouseReleased'])await cdp('Input.dispatchMouseEvent',{type,x:point.x,y:point.y,button:'left',clickCount:1});};
  const navigate=async()=>{const previous=await evaluate('window.__sidebar_boot');await cdp('Page.navigate',{url:pathToFileURL(htmlPath).href});await waitFor(`window.__sidebar_boot!==${JSON.stringify(previous)} && typeof switchScreen==='function'`);};
  await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1280,height:820,deviceScaleFactor:1,mobile:false});await cdp('Page.addScriptToEvaluateOnNewDocument',{source:bridge});await navigate();
  const check=async(name,fn)=>{try{await navigate();await fn();results.push({name,ok:true});}catch(error){results.push({name,ok:false,error:error.stack||error.message});}};
  await check('sidebar_starts_expanded',async()=>{assert.equal(await evaluate(`document.getElementById('app-layout').classList.contains('sidebar-collapsed')`),false);assert.equal(await evaluate(`document.getElementById('btn-sidebar-toggle').getAttribute('aria-expanded')`),'true');assert((await evaluate(`getComputedStyle(document.querySelector('.sidebar')).width`)).includes('184'));assert((await evaluate(`document.getElementById('btn-sidebar-toggle').getBoundingClientRect().width`))>=28,'Sidebar toggle hit target shrank below 28px');});
  await check('sidebar_collapses_and_keeps_navigation',async()=>{await click('#btn-sidebar-toggle');assert.equal(await evaluate(`document.getElementById('app-layout').classList.contains('sidebar-collapsed')`),true);assert.equal(await evaluate(`document.getElementById('btn-sidebar-toggle').getAttribute('aria-expanded')`),'false');assert.equal(await evaluate(`document.querySelector('.brand-name').getBoundingClientRect().width`),0);assert((await evaluate(`document.getElementById('btn-sidebar-toggle').getBoundingClientRect().width`))>=28,'Collapsed sidebar toggle hit target shrank below 28px');await click('[data-screen="security"]');assert.equal(await evaluate('ACTIVE_SCREEN'),'security');assert.equal(await evaluate(`document.querySelector('.nav-btn[data-screen="security"] .icon').getBoundingClientRect().width>0`),true);});
  await check('sidebar_state_survives_reload',async()=>{await evaluate(`localStorage.setItem('skillradar-sidebar-collapsed','true')`);await navigate();assert.equal(await evaluate(`document.getElementById('app-layout').classList.contains('sidebar-collapsed')`),true);});
  await check('sidebar_keyboard_toggle',async()=>{await evaluate(`localStorage.setItem('skillradar-sidebar-collapsed','false');SIDEBAR_COLLAPSED=false;paintSidebar()`);const button='#btn-sidebar-toggle';await evaluate(`document.querySelector(${JSON.stringify(button)}).focus()`);await key('Enter','Enter',13);assert.equal(await evaluate(`document.getElementById('app-layout').classList.contains('sidebar-collapsed')`),true);await key(' ','Space',32);assert.equal(await evaluate(`document.getElementById('app-layout').classList.contains('sidebar-collapsed')`),false);assert.equal(await evaluate(`document.activeElement.id`),'btn-sidebar-toggle');});
  await check('sidebar_fits_narrow_desktop',async()=>{await cdp('Emulation.setDeviceMetricsOverride',{width:860,height:560,deviceScaleFactor:1,mobile:false});await click('#btn-sidebar-toggle');const layout=await evaluate(`(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1||document.getElementById('main-content').scrollWidth>document.getElementById('main-content').clientWidth+1,sidebar:getComputedStyle(document.querySelector('.sidebar')).width}))()`);assert.equal(layout.overflow,false);});
  await check('sidebar_mobile_restores_brand',async()=>{await cdp('Emulation.setDeviceMetricsOverride',{width:640,height:820,deviceScaleFactor:1,mobile:false});await evaluate(`localStorage.setItem('skillradar-sidebar-collapsed','true');SIDEBAR_COLLAPSED=true;paintSidebar()`);const mobile=await evaluate(`(()=>{const sidebar=document.querySelector('.sidebar'),brand=document.querySelector('.brand'),name=document.querySelector('.brand-name'),rect=name.getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth+1,sidebar:sidebar.getBoundingClientRect().width,brand:brand.getBoundingClientRect().toJSON(),name:rect.toJSON(),toggle:getComputedStyle(document.getElementById('btn-sidebar-toggle')).display}})()`);assert.equal(mobile.overflow,false);assert.equal(mobile.toggle,'none');assert(mobile.brand.width>100,'Mobile brand should restore full width');assert(mobile.name.left>=mobile.brand.left && mobile.name.right<=mobile.brand.right,'Mobile brand text must stay inside brand');});
}catch(error){results.push({name:'harness',ok:false,error:error.stack||error.message});}finally{try{if(cdp)await cdp('Browser.close')}catch{}if(ws)ws.close();if(browser&&browser.exitCode===null){browser.kill();await Promise.race([new Promise(resolve=>browser.once('exit',resolve)),pause(2000)]);}assert(profile.startsWith(resolve(tmpdir())+sep)&&basename(profile).startsWith('skill-radar-sidebar-'));try{rmSync(profile,{recursive:true,force:true,maxRetries:6,retryDelay:150})}catch{}}
console.log(JSON.stringify({html:htmlPath,results}));process.exitCode=results.some(result=>!result.ok)?1:0;
