// Chromium interaction checks for batch actions, using an isolated fake desktop bridge.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {existsSync,readFileSync,writeFileSync,mkdtempSync,rmSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {basename,dirname,resolve,sep} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const repo=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const args=process.argv.slice(2), option=name=>args.includes(name)?args[args.indexOf(name)+1]:null;
const browserPath=option('--browser') || process.env.SKILL_RADAR_BROWSER;
assert(browserPath && existsSync(browserPath),'Provide Chromium with --browser');
const htmlPath=resolve(option('--html') || resolve(repo,'tray/web/index.html'));
const captureDir=option('--capture'), prefix=option('--prefix') || 'idle';
const width=Number(option('--width') || 1080),height=Number(option('--height') || 720);
const language=option('--language') || 'zh-CN', profile=mkdtempSync(resolve(tmpdir(),'skill-radar-idle-ui-'));
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const installed=(name,extra={})=>({name,path:'F:/Skills/'+name,total:0,codex:0,zcode:0,claude:0,marker:0,last:null,installed_at:'2026-08-01T02:03:04Z',updated_at:'2026-09-01T04:05:06Z',install_time_source:'file_creation_time',usage_state:'never',shared_name:false,observing:false,...extra});
const never=Array.from({length:28},(_,i)=>installed('unused-'+String(i+1).padStart(2,'0')));
never.push(installed('fresh',{observing:true,installed_at:'2026-10-04T02:03:04Z'}),installed('<img src=x onerror="window.__unsafe=true">',{path:'F:/Skills/<svg onload="window.__unsafe=true">'}));
const inactive=[installed('same-name',{path:'F:/First/same-name',total:4,codex:4,last:'2026-08-01T06:07:08Z',usage_state:'inactive',shared_name:true}),installed('same-name',{path:'F:/Second/same-name',total:4,codex:4,last:'2026-08-01T06:07:08Z',usage_state:'inactive',shared_name:true})];
const unknown=[installed('undated',{total:1,usage_state:'unknown'})];
const usage={ok:true,rows:[{name:'many-old',total:20,codex:20,last:'2026-09-01T10:20:00Z'},{name:'one-new',total:1,codex:1,last:'2026-10-04T12:20:00Z'},...Array.from({length:30},(_,i)=>({name:'rank-'+(i+1),total:i+1,codex:i+1,zcode:0,claude:0,marker:0,last:'2026-10-04T10:20:00Z'}))],installed_rows:[...never,...inactive,...unknown,installed('active',{total:6,last:'2026-10-04T10:20:00Z',usage_state:'active'})],idle_groups:{never,inactive,unknown},inventory_summary:{total_installed:34,never:30,inactive:2,unknown:1,active:1,total_invocations:10,coverage_complete:true,coverage_note:'Ready; invocation records match skill names.'},status:{phase:'ready',scanning:false,files_scanned:12,last_scan:'2026-10-04T10:35:00Z',roots:[{source:'codex',path:'F:/Logs/sessions',exists:true}],errors:[]}};
const state={guard:'running',watched_roots:1,settings:{language:'zh-CN',roots:[{path:'F:/Skills'}]},skills:{'F:/Skills/security-demo':{name:'security-demo',score:0,status:'scanned',version:'v1',findings:[],raw_findings:[],raw_score:0,scan_complete:true,scan_issues:[],check_status:'healthy',review_status:'not_required',installed_at:'2026-08-01T02:03:04Z',updated_at:'2026-09-01T04:05:06Z',install_time_source:'file_creation_time',scanned_at:'2026-10-04T10:11:12Z'}},events:[]};
const bridge=`window.__batch_boot=crypto.randomUUID();window.__batch_state=${JSON.stringify(state)};window.__usage_data=${JSON.stringify(usage)};window.__usage_error=false;window.__usage_delay=0;window.__batch_actions=[];
try{localStorage.clear();}catch{}
window.pywebview={api:{get_state:async()=>structuredClone(window.__batch_state),act:async(name,payload)=>{
window.__batch_actions.push({name,payload});
if(name==='set_language'){window.__batch_state.settings.language=payload.language;return{ok:true};}
if(name==='get_usage'){if(window.__usage_delay)await new Promise(r=>setTimeout(r,window.__usage_delay));return window.__usage_error?{error:'permission denied'}:structuredClone(window.__usage_data);}
if(name==='get_markdown')return {ok:true,markdown:'# Security result\\n\\n'+payload.skill};
if(name==='list_reports')return {ok:true,reports:[]};
return{ok:true};
}}};`;
let browser,ws,closeBrowser;const results=[];
try{
browser=spawn(browserPath,['--headless=new','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
browser.on('error',error=>results.push({name:'browser_start',ok:false,error:error.message}));
const portFile=resolve(profile,'DevToolsActivePort');let until=Date.now()+12000;
while(!existsSync(portFile)&&Date.now()<until)await pause(40);
assert(existsSync(portFile),'Chromium did not expose its temporary endpoint');
const port=readFileSync(portFile,'utf8').split(/\r?\n/)[0];
const target=(await(await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(p=>p.type==='page');
ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((ok,fail)=>{ws.addEventListener('open',ok,{once:true});ws.addEventListener('error',fail,{once:true});});
let id=0;const pending=new Map();
ws.addEventListener('message',event=>{const data=JSON.parse(event.data),request=pending.get(data.id);if(!request)return;pending.delete(data.id);clearTimeout(request.timeout);data.error?request.reject(new Error(JSON.stringify(data.error))):request.resolve(data.result);});
const cdp=(method,params={})=>new Promise((ok,fail)=>{const current=++id,timeout=setTimeout(()=>{pending.delete(current);fail(new Error('CDP timeout '+method));},8000);pending.set(current,{resolve:ok,reject:fail,timeout});ws.send(JSON.stringify({id:current,method,params}));});
closeBrowser=()=>cdp('Browser.close');
const evaluate=async expression=>{const value=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});assert(!value.exceptionDetails,JSON.stringify(value.exceptionDetails));return value.result.value;};
const waitFor=async expression=>{const deadline=Date.now()+2000;while(Date.now()<deadline){if(await evaluate(expression))return;await pause(25);}throw new Error('UI condition: '+expression);};
const click=async selector=>{const point=await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});if(!el)return null;el.scrollIntoView({block:'center'});const r=el.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,width:r.width,height:r.height};})()`);assert(point?.width&&point.height,'Missing visible target: '+selector);for(const type of ['mousePressed','mouseReleased'])await cdp('Input.dispatchMouseEvent',{type,x:point.x,y:point.y,button:'left',clickCount:1});};
const key=async(key,code,keyCode)=>{for(const type of ['keyDown','keyUp'])await cdp('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:keyCode,nativeVirtualKeyCode:keyCode});};
const search=async query=>evaluate(`(()=>{const input=document.getElementById('skill-search');input.value=${JSON.stringify(query)};input.dispatchEvent(new Event('input',{bubbles:true}));})()`);
const sync=()=>evaluate('tick()');
await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Emulation.setTimezoneOverride',{timezoneId:'Asia/Singapore'});
await cdp('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});
await cdp('Page.addScriptToEvaluateOnNewDocument',{source:bridge});
const reset=async()=>{const previous=await evaluate('window.__batch_boot');await cdp('Page.navigate',{url:pathToFileURL(htmlPath).href});await waitFor(`window.__batch_boot!==${JSON.stringify(previous)} && !!document.querySelector('#sec-rows tr[data-skill]')`);await click('nav.sidebar button[data-screen="security"]');};
const screenshot=async(name,scroll=0)=>{if(!captureDir)return;await evaluate(`document.getElementById('toast').classList.remove('show');if(document.getElementById('drawer').hidden)document.getElementById('main-content').scrollTop=${scroll}`);mkdirSync(captureDir,{recursive:true});const audit=await evaluate(`(()=>{const main=document.getElementById('main-content'),drawer=document.getElementById('drawer');return{overflow:document.documentElement.scrollWidth>innerWidth+1||main.scrollWidth>main.clientWidth+1||(!drawer.hidden&&drawer.scrollWidth>drawer.clientWidth+1)};})()`);results.push({name:'layout_'+name,ok:!audit.overflow,...audit});const data=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(resolve(captureDir,prefix+'-'+name+'.png'),Buffer.from(data.data,'base64'));};
const check=async(name,fn)=>{try{await reset();await fn();results.push({name,ok:true});}catch(error){results.push({name,ok:false,error:error.stack||error.message});}};

const openUsage=async()=>{await click('nav.sidebar button[data-screen="usage"]');await waitFor(`USAGE_PHASE==='ready'`);};
const content=id=>evaluate(`document.getElementById(${JSON.stringify(id)}).innerText`);
const redraw=()=>evaluate('loadUsage(false,true)');
await check('default_idle_complete_groups',async()=>{await openUsage();assert.equal(await evaluate(`document.querySelector('[data-usage-view="idle"]').getAttribute('aria-pressed')`),'true');assert.equal(await evaluate(`document.querySelectorAll('#usage-group-never tbody tr').length`),30);assert.equal(await evaluate(`document.querySelectorAll('#usage-group-inactive tbody tr').length`),2);assert.equal(await evaluate(`document.querySelectorAll('#usage-group-unknown tbody tr').length`),1);const text=await content('usage-detail');assert(!text.includes('rank-'));assert(text.includes('观察中')&&text.includes('同名技能共用调用记录')&&text.includes('F:/Second/same-name'));const summary=await content('usage-bars');assert(summary.includes('34')&&summary.includes('10'));await screenshot('idle');await screenshot('idle-rows',400);});
await check('ranking_all_rows',async()=>{await openUsage();await click('[data-usage-view="ranking"]');assert.equal(await evaluate(`document.querySelectorAll('#usage-detail tbody tr').length`),32);assert.equal(await evaluate(`document.querySelector('#usage-detail tbody tr:first-child td').innerText`),'one-new');assert((await content('usage-detail')).includes('rank-1'));assert((await content('usage-bars')).includes('20'));assert((await content('usage-view-description')).includes('按最近记录时间排序'));await screenshot('ranking');});
await check('selection_survives_refresh_and_language',async()=>{await openUsage();await click('[data-usage-view="ranking"]');await click('#btn-refresh-usage');await waitFor(`USAGE_PHASE==='ready'`);assert.equal(await evaluate(`document.querySelector('[data-usage-view="ranking"]').getAttribute('aria-pressed')`),'true');await evaluate(`changeLanguage('en')`);assert.equal(await evaluate(`document.querySelector('[data-usage-view="ranking"]').getAttribute('aria-pressed')`),'true');assert((await content('usage-detail')).includes('Last recorded'));await click('[data-usage-view="idle"]');assert((await content('usage-detail')).includes('No invocation records'));await evaluate(`changeLanguage('zh-CN')`);assert.equal(await evaluate(`document.querySelector('[data-usage-view="idle"]').getAttribute('aria-pressed')`),'true');});
await check('zero_usage_installed_skill',async()=>{await openUsage();await evaluate(`window.__usage_data.rows=[];window.__usage_data.installed_rows=[window.__usage_data.idle_groups.never[0]];window.__usage_data.idle_groups={never:window.__usage_data.installed_rows,inactive:[],unknown:[]};window.__usage_data.inventory_summary={total_installed:1,never:1,inactive:0,unknown:0,active:0,total_invocations:0,coverage_complete:true}`);await redraw();assert((await content('usage-detail')).includes('unused-01'));assert.equal(await evaluate(`document.querySelectorAll('#usage-group-never tbody tr').length`),1);});
await check('empty_inventory',async()=>{await openUsage();await evaluate(`window.__usage_data.rows=[];window.__usage_data.installed_rows=[];window.__usage_data.idle_groups={never:[],inactive:[],unknown:[]};window.__usage_data.inventory_summary={total_installed:0,never:0,inactive:0,unknown:0,active:0,total_invocations:0,coverage_complete:true}`);await redraw();assert((await content('usage-detail')).includes('暂无已安装技能'));assert((await content('usage-bars')).includes('0'));});
await check('unavailable_inventory_root',async()=>{await openUsage();await evaluate(`window.__usage_data.rows=[];window.__usage_data.installed_rows=[];window.__usage_data.idle_groups={never:[],inactive:[],unknown:[]};window.__usage_data.inventory_summary={total_installed:0,never:0,inactive:0,unknown:0,active:0,total_invocations:0,coverage_complete:false,inventory_complete:false,unavailable_inventory_roots:['F:/Missing']}`);await redraw();assert((await content('usage-detail')).includes('技能清单不完整'));assert(!(await content('usage-detail')).includes('暂无已安装技能'));assert((await content('usage-detail')).includes('F:/Missing'));});
await check('partial_coverage',async()=>{await openUsage();await evaluate(`window.__usage_data.status.scanning=true;window.__usage_data.status.phase='scanning';window.__usage_data.rows=[];window.__usage_data.idle_groups={never:[],inactive:[],unknown:[{...window.__usage_data.installed_rows[0],usage_state:'unknown'}]};window.__usage_data.installed_rows=window.__usage_data.idle_groups.unknown;window.__usage_data.inventory_summary={total_installed:1,never:0,inactive:0,unknown:1,active:0,total_invocations:0,coverage_complete:false,coverage_note:'History scan incomplete'}`);await redraw();assert((await content('usage-detail')).includes('记录不足'));assert((await content('usage-coverage')).includes('History scan incomplete'));assert((await content('usage-scan-status')).includes('正在后台扫描'));assert.equal(await evaluate(`document.querySelectorAll('#usage-group-unknown tbody tr').length`),1);});
await check('legacy_inventory_unavailable',async()=>{await openUsage();await evaluate(`delete window.__usage_data.installed_rows;delete window.__usage_data.inventory_summary;delete window.__usage_data.idle_groups`);await redraw();assert((await content('usage-detail')).includes('技能清单未提供'));assert((await content('usage-bars')).includes('—'));await click('[data-usage-view="ranking"]');assert.equal(await evaluate(`document.querySelectorAll('#usage-detail tbody tr').length`),32);});
await check('loading_and_error',async()=>{await openUsage();await evaluate(`window.__usage_delay=400;void loadUsage(false,true)`);assert((await content('usage-bars')).includes('—'));assert((await content('usage-detail')).includes('正在读取'));await waitFor(`USAGE_PHASE==='ready'`);await evaluate(`window.__usage_error=true`);await redraw();assert((await content('usage-detail')).includes('permission denied'));assert((await content('usage-bars')).includes('—'));assert.equal(await evaluate(`document.getElementById('btn-refresh-usage').disabled`),false);});
await check('safe_user_data',async()=>{await openUsage();assert.equal(await evaluate(`window.__unsafe`),undefined);assert.equal(await evaluate(`document.querySelector('#usage-detail img,#usage-detail svg[onload]')`),null);assert((await content('usage-detail')).includes('<img src=x'));});
await check('discovery_collapsed_with_status',async()=>{await openUsage();assert.equal(await evaluate(`document.getElementById('usage-log-details')?.open`),false);assert((await content('usage-scan-status')).includes('历史日志扫描完成'));await click('#usage-log-details > summary');assert((await content('usage-discovery')).includes('F:/Logs/sessions'));assert((await content('usage-discovery')).includes('会话日志'));});
await check('direct_status_over_stale_state',async()=>{await openUsage();await evaluate(`CURRENT.usage_status={phase:'ready',scanning:false};window.__usage_data.status.scanning=true;window.__usage_data.status.phase='scanning'`);await redraw();assert((await content('usage-scan-status')).includes('正在后台扫描'));assert.equal(await evaluate(`document.getElementById('btn-select-usage-dir').disabled`),true);});
await check('observation_and_duplicate_explanations',async()=>{await openUsage();assert((await evaluate(`document.querySelector('[data-usage-observing]').title`)).includes('30 天'));assert((await evaluate(`document.querySelector('[data-usage-shared-name]').title`)).includes('无法确认'));});
await check('english_coverage_notes',async()=>{await openUsage();await evaluate(`window.__usage_data.inventory_summary.coverage_note='会话日志尚未完成采集；部分会话日志读取失败。零调用技能显示为记录不足；已知调用仅反映已采集日志。';window.__usage_data.inventory_summary.coverage_complete=false`);await redraw();await evaluate(`changeLanguage('en')`);const note=await content('usage-coverage');assert(note.includes('Session-log collection is incomplete'));assert(note.includes('Some session logs could not be read'));assert(!/[\u4e00-\u9fff]/.test(note));});
await check('security_file_times',async()=>{const text=await content('sec-rows');assert(text.includes('安装时间（估算）')&&text.includes('2026年08月01日 10:03:04')&&text.includes('更新时间')&&text.includes('2026年09月01日 12:05:06'));await click('#sec-rows tr[data-skill]');const detail=await content('drawer-body');assert(detail.includes('安装时间（估算）')&&detail.includes('2026年08月01日 10:03:04'));assert(detail.includes('检查时间')&&detail.includes('2026-10-04T10:11:12Z'));assert(detail.includes('创建时间')&&detail.includes('复制'));await screenshot('security-detail');await click('#btn-close-drawer');await screenshot('security-list');});
await check('unknown_file_times',async()=>{await evaluate(`delete window.__batch_state.skills['F:/Skills/security-demo'].installed_at;delete window.__batch_state.skills['F:/Skills/security-demo'].updated_at;void tick()`);await waitFor(`document.getElementById('sec-rows').innerText.includes('安装时间（估算） · 未知')`);await click('#sec-rows tr[data-skill]');assert((await content('drawer-body')).includes('更新时间 · 未知'));});
await check('english_file_times_and_report',async()=>{await evaluate(`changeLanguage('en')`);const text=await content('sec-rows');assert(text.includes('Installed at (estimated)')&&text.includes('2026-08-01 10:03:04'));await click('#sec-rows tr[data-skill]');assert((await content('drawer-body')).includes('Updated at'));await click('#btn-close-drawer');await click('nav.sidebar button[data-screen="reports"]');assert((await content('report-help')).includes('You decide how to proceed'));assert((await content('report-help')).includes('Run checks before generating'));await screenshot('report');await openUsage();assert((await content('usage-detail')).includes('Observing'));await screenshot('idle-en');await screenshot('idle-rows-en',400);});
await check('small_window',async()=>{await cdp('Emulation.setDeviceMetricsOverride',{width:860,height:560,deviceScaleFactor:1,mobile:false});await openUsage();await screenshot('idle-small');await screenshot('idle-rows-small',400);await click('[data-usage-view="ranking"]');await screenshot('ranking-small');await screenshot('ranking-rows-small',400);await click('nav.sidebar button[data-screen="security"]');await screenshot('security-small');await click('#sec-rows tr[data-skill]');await screenshot('detail-small');assert.equal(await evaluate(`document.documentElement.scrollWidth>innerWidth+1||document.getElementById('main-content').scrollWidth>document.getElementById('main-content').clientWidth+1||document.getElementById('drawer').scrollWidth>document.getElementById('drawer').clientWidth+1`),false);});
}catch(error){results.push({name:'harness',ok:false,error:error.stack||error.message});}
finally{try{if(closeBrowser)await closeBrowser();}catch{}if(ws)ws.close();if(browser&&browser.exitCode===null){browser.kill();await Promise.race([new Promise(resolve=>browser.once('exit',resolve)),pause(2000)]);}assert(profile.startsWith(resolve(tmpdir())+sep)&&basename(profile).startsWith('skill-radar-idle-ui-'));try{rmSync(profile,{recursive:true,force:true,maxRetries:6,retryDelay:150});}catch{}}
console.log(JSON.stringify({html:htmlPath,browser:browserPath,results}));process.exitCode=results.some(row=>!row.ok)?1:0;
